name: 'vm2m_hmm_short-768-512x512_bs16_100k_adamw_2e-4'
train:
  batch_size: 16
  num_workers: 12
  max_iter: 100000
  optimizer:
    lr: 0.0002
    name: adamw
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
output_dir: 'output'
dataset:
  train:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'train'
  test:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'val'