name: 'vm2m_short-768-512x512_bs32_50k_adamw_2e-4'
output_dir: 'output/HHM'
train:
  batch_size: 32
  num_workers: 4
  max_iter: 50000
  optimizer:
    lr: 0.0002
    name: adamw
  val_metrics: ['BgMAD', 'FgMAD', 'TransMAD', 'MAD', 'MSE']
  val_best_metric: 'MAD'
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
model:
  loss_dtSSD_w: 0.0
  loss_comp_w: 0.0
dataset:
  train:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'train'
  test:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'val'