name: 'vm2m0711_hhm_short-768-512x512_bs32_50k_adamw_2e-4'
model:
  arch: 'VM2M0711'
  backbone: 'res_shortcut_encoder_29'
  backbone_args:
    num_mask: 0
  dynamic_kernel:
    out_incoherence: 137
    out_pixeldecoder: 864
  mgm:
    warmup_iter: 5000
  loss_dtSSD_w: 0.0
  loss_comp_w: 0.0
train:
  optimizer:
    lr: 0.0002
    name: adamw
  val_iter: 1000
  val_metrics: ['MAD', 'MSE']
  val_best_metric: 'MAD'
  vis_iter: 200
  log_iter: 50
  batch_size: 32
  num_workers: 10
  max_iter: 50000
output_dir: 'output/HHM'
dataset:
  train:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'train'
  test:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'val'