name: 'mgm_him_short-768-512x512_bs32_50k_adamw_2e-4'
output_dir: 'output/HIM'
train:
  batch_size: 8
  num_workers: 4
  max_iter: 50000
  optimizer:
    lr: 0.0002
    name: adamw
  val_metrics: ['MAD', 'MSE', 'SAD']
  val_best_metric: 'MAD'
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
  seed: 1105
test:
  num_workers: 4
  metrics: ['MAD', 'MSE', 'SAD', 'Conn', 'Grad']
model:
  arch: 'MGM'
  backbone: 'res_shortcut_encoder_29'
  backbone_args:
    num_mask: 10
  decoder: 'res_shortcut_decoder_22'
  decoder_args:
    max_inst: 10
  mgm:
    warmup_iter: 5000
  loss_dtSSD_w: 0.0
  loss_comp_w: 0.0
dataset:
  train:
    name: 'HIM'
    root_dir: '/mnt/localssd/HHM'
    bg_dir: '/mnt/localssd/bg'
    split: 'train'
  test:
    name: 'HIM'
    root_dir: '/mnt/localssd/HIM2K'
    split: 'comp'