name: 'sweep'
output_dir: 'output/HIM'
train:
  batch_size: 12
  num_workers: 4
  max_iter: 10000
  optimizer:
    lr: 2.0e-4
    name: adamw
  scheduler:
    name: cosine
    warmup_iters: 1000
  val_metrics: ['MAD', 'MSE', 'SAD']
  val_best_metric: 'MAD'
  val_iter: 500
  vis_iter: 100
  log_iter: 10
  seed: 1234
test:
  num_workers: 4
  metrics: ['MAD', 'MSE', 'SAD']
  log_iter: 10
model:
  arch: 'MGM'
  backbone: 'res_embed_shortcut_encoder_29'
  backbone_args:
    num_mask: 10
    num_embed: 3
  decoder: 'res_shortcut_embed_attention_decoder_22'
  decoder_args:
    max_inst: 10
    final_channel: 64
    # atten_dims: [32, 32, 32]
    atten_dim: 128
    atten_stride: 1
    atten_block: 2
    atten_head: 1
    head_channel: 32 
  mgm:
    warmup_iter: 5000
  loss_dtSSD_w: 0.0
  loss_comp_w: 0.0
dataset:
  train:
    name: 'HIM'
    root_dir: '/mnt/localssd/HHM'
    bg_dir: '/mnt/localssd/bg'
    split: 'train'
    max_inst: 3
    short_size: 576
  test:
    name: 'HIM'
    root_dir: '/mnt/localssd/HIM2K'
    split: 'comp'
    short_size: 576