dataset:
  test:
    alpha_dir_name: alphas
    clip_length: 8
    clip_overlap: 2
    downscale_mask: false
    mask_dir_name: 'masks_matched_r50_fpn_3x'
    name: HIM
    random_seed: 2023
    root_dir: /mnt/localssd/HIM2K
    short_size: 576
    split: natural
    use_thresh_mask: false
  train:
    bg_dir: ''
    bin_alpha_max_k: 30
    blur_kernel_size:
    - 5
    - 15
    - 25
    blur_prob: 0.5
    blur_sigma:
    - 1.0
    - 1.5
    - 3.0
    - 5.0
    clip_length: 8
    crop:
    - 512
    - 512
    downscale_mask: false
    downscale_mask_p: 0.5
    flip_prob: 0.5
    mask_dir_name: masks_matched
    max_inst: 3
    max_step_size: 2
    modify_mask_p: 0.1
    name: HIM
    padding_inst: 10
    pha_dir: pha
    random_state: 2023
    root_dir: /mnt/localssd/HHM
    short_size: 576
    split: synthesized
    use_maskrcnn_p: 0.2
    use_single_instance_only: true
    weight_mask_dir: ''
model:
  arch: MGM
  having_unused_params: false
  freeze_coarse: false
  aspp:
    in_channels: 512
    out_channels: 512
  # backbone: res_embed_shortcut_os8_encoder_29
  backbone: res_embed_shortcut_encoder_29
  backbone_args:
    num_embed: 3
    num_mask: 10
    pretrained: true
  breakdown:
    in_channels:
    - 32
    - 32
    - 32
    in_features:
    - os4
    - os1
  decoder: res_shortcut_attention_spconv_decoder_22_new
  decoder_args:
    atten_block: 2
    atten_dim: 128
    atten_head: 1
    atten_stride: 1
    detail_mask_dropout: 0.1
    final_channel: 64
    head_channel: 120
    max_inst: 10
    use_id_pe: true
    warmup_detail_iter: 0
    warmup_mask_atten_iter: 0
    freeze_detail_branch: false
  dynamic_kernel:
    dec_layers: 5
    dim_feedforward: 256
    enforce_input_project: true
    hidden_dim: 256
    in_channels: 256
    in_features:
    - os32
    - os16
    - os8
    nheads: 4
    out_incoherence: 157
    out_pixeldecoder: 864
    pre_norm: false
  loss_alpha_grad_w: 0.05
  loss_alpha_lap_w: 0.05
  loss_alpha_type: l1
  loss_alpha_w: 1.0
  loss_atten_w: 5.0
  loss_comp_w: 0.0
  loss_dtSSD_w: 0.0
  loss_multi_inst_type: smooth_l1_0.5
  loss_multi_inst_w: 5.0
  loss_multi_inst_warmup: 0
  mgm:
    warmup_iter: 0
  refinement:
    n_test_points: 16000
    n_train_points: 2048
  shm:
    dilation_kernel: 15
    lr_scale: 0.5
    max_n_pixel: 4000000
    mgm_weights: ''
  shortcut_dims:
  - 32
  - 32
  - 64
  - 128
  - 256
  sync_bn: true
  weights: 'output/HIM/ours_1102_single-stage_strong-aug/best_model.pth'
name: ours_1023
output_dir: output/HIM
test:
  batch_size: 1
  log_iter: 100
  metrics:
  - MAD
  - MSE
  - SAD
  # - Grad
  # - Conn
  num_workers: 4
  postprocessing: false
  save_dir: logs
  save_results: true
  temp_aggre: false
  use_trimap: true
train:
  batch_size: 24
  log_iter: 10
  # max_iter: 26000
  max_iter: 8000
  num_workers: 8
  optimizer:
    betas:
    - 0.9
    - 0.999
    lr: 0.00005
    momentum: 0.9
    name: adamw
    weight_decay: 0.01
  resume: ''
  resume_last: true
  scheduler:
    gamma: 0.1
    name: cosine
    power: 0.9
    step_size: 10000
    warmup_iters: 500
  seed: 1234
  val_best_metric: MAD
  val_dist: true
  val_iter: 500
  val_metrics:
  - MAD
  - MSE
  - SAD
  vis_iter: 50
wandb:
  entity: research-dmo
  id: ''
  project: video-maskg-matting
  use: true