name: 'mgm_vid240_pre-hmm_s-768-512x512_b4-f8_100k_adamw_1e-4'
model:
  arch: 'MGM'
  weights: ''
  backbone: 'res_shortcut_encoder_29'
  mgm:
    warmup_iter: 5000
train:
  optimizer:
    lr: 0.0001
    name: adamw
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
  batch_size: 16
  num_workers: 4
  seed: 1629
output_dir: 'output/VideoMatte240K'
dataset:
  train:
    root_dir: '/mnt/localssd/VideoMatte240K'
    bg_dir: '/mnt/localssd/bg'
    short_size: 768
    clip_length: 1
  test:
    root_dir: '/mnt/localssd/VideoMatte240K'
    short_size: 768
    clip_length: 1
    clip_overlap: 0