name: 'mgm_vid240_pre-hmm_s-768-512x512_b4-f8_100k_adamw_1e-4'
model:
  arch: 'MGM'
  weights: 'output/HHM/mgm_hmm_short-768-512x512_bs32_50k_adamw_2e-4/best_model.pth'
  backbone: 'res_shortcut_encoder_29'
  mgm:
    warmup_iter: 0
  loss_dtSSD_w: 0.0
  loss_comp_w: 1.0
train:
  optimizer:
    lr: 0.0001
    name: adamw
  val_metrics: ['MAD', 'MSE', 'dtSSD']
  val_best_metric: 'MAD'
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
  batch_size: 32
  num_workers: 4
  max_iter: 100000
output_dir: 'output/VideoMatte240K'
test:
  num_workers: 4
dataset:
  train:
    root_dir: '/mnt/localssd/VideoMatte240K'
    bg_dir: '/mnt/localssd/bg'
    short_size: 768
    clip_length: 1
  test:
    root_dir: '/mnt/localssd/VideoMatte240K'
    short_size: 768
    clip_length: 1
    clip_overlap: 0