name: 'ours_vhm_0927_ss_new'
output_dir: 'output/VHM'
train:
  batch_size: 4
  num_workers: 8
  max_iter: 20000
  optimizer:
    lr: 1.0e-5
    name: adamw
  scheduler:
    name: cosine
    warmup_iters: 1000
  val_metrics: ['MAD', 'MSE', 'SAD', 'dtSSD']
  val_best_metric: 'dtSSD'
  val_iter: 200
  vis_iter: 50
  log_iter: 10
  val_dist: True
  resume_last: True
  seed: 1105
test:
  num_workers: 4
  metrics: ['MAD', 'MSE', 'SAD', 'dtSSD']
  temp_aggre: False
model:
  arch: MGM_SS
  sync_bn: False
  weights: output/VHM/ours_vhm_0919/best_model.pth
  backbone: res_embed_shortcut_os8_encoder_29
  backbone_args:
    num_embed: 3
    num_mask: 10
    pretrained: true
    shortcut_dropout: 0.0
  decoder: res_shortcut_attention_spconv_temp_decoder_22
  decoder_args:
    atten_block: 2
    atten_dim: 128
    atten_head: 1
    atten_stride: 1
    embed_dim: 3
    final_channel: 64
    head_channel: 120
    max_inst: 10
    stm_dropout: 0.0
    use_detail_temp: false
    use_query_temp: false
    warmup_mask_atten_iter: 0
    warmup_detail_iter: 0
  mgm:
    warmup_iter: 0
  loss_alpha_grad_w: 0.0
  loss_alpha_lap_w: 1.0
  loss_alpha_type: l1
  loss_alpha_w: 1.0
  loss_atten_w: 1.0
  loss_comp_w: 0.0
  loss_dtSSD_w: 1.0
  loss_multi_inst_w: 0.25
  loss_multi_inst_type: smooth_l1_0.5
  loss_multi_inst_warmup: 0
dataset:
  train:
    name: 'CombineMultiInstVideo'
    root_dir: '/mnt/localssd/'
    bg_dir: ''
    split: 'train'
    short_size: 576
    max_inst: 2
    clip_length: 3
    max_step_size: 5
    padding_inst: 10
    random_state: 2023
    modify_mask_p: 0.1
    downscale_mask_p: 0.5
    pha_dir: 'pha'
    weight_mask_dir: 'weight_mask'
  test:
    name: 'MultiInstVideo'
    root_dir: '/mnt/localssd/syn/benchmark'
    split: 'comp_medium'
    short_size: 576
    clip_length: 8
    clip_overlap: 2
    use_thresh_mask: False
    mask_dir_name: ''