name: 'mgm_multi-inst'
output_dir: 'output/AIM-500'
train:
  batch_size: 32
  num_workers: 4
  max_iter: 50000
  optimizer:
    lr: 0.0002
    name: adamw
  val_metrics: ['BgMAD', 'FgMAD', 'TransMAD', 'MAD', 'MSE']
  val_best_metric: 'MAD'
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
  seed: 1105
test:
  num_workers: 4
  metrics: ['MAD', 'MSE', 'SAD']
  postprocessing: False
  use_trimap: False
  log_iter: 1
  save_results: False
model:
  arch: 'MGM'
  backbone: 'res_embed_shortcut_encoder_29'
  backbone_args:
    num_mask: 10
  decoder: 'res_shortcut_embed_attention_decoder_22'
  decoder_args:
    max_inst: 10
    final_channel: 64
    # atten_dims: [32, 32, 32]
    atten_dims: [64, 64, 128]
    atten_strides: [4, 2, 1]
    atten_blocks: [2, 2, 2]
    atten_heads: [1, 1, 1]
  mgm:
    warmup_iter: 5000
  loss_dtSSD_w: 0.0
  loss_comp_w: 0.0
dataset:
  train:
    name: 'HHM'
    root_dir: '/mnt/localssd/HHM'
    split: 'train'
  test:
    name: 'HHM'
    root_dir: '/mnt/localssd/AIM-500'
    split: 'test'