dataset:
  test:
    name: HIM
    root_dir: data/HIM2K_M-HIM2K
    split: comp
    short_size: 576
    downscale_mask: false
    alpha_dir_name: alphas
    mask_dir_name: masks_matched_r50_fpn_3x
  train:
    name: HIM
    root_dir: data
    split: I-HIM50K
    short_size: 576
    random_state: 2023
    max_inst: 10
    crop:
    - 512
    - 512
    padding_crop_p: 0.1
    flip_p: 0.5
    gamma_p: 0.5
    add_noise_p: 0.3
    jpeg_p: 0.1
    affine_p: 0.1
    binarized_kernel: 30
    downscale_mask_p: 0.5
    mask_dir_name: ''
    alpha_dir_name: alphas
model:
  arch: MaGGIe
  weights: chuonghm/maggie-image-him50k-cvpr24
  sync_bn: true
  having_unused_params: true
  warmup_iters: 3000
  encoder: res_shortcut_embed_29
  encoder_args:
    num_embed: 3
    num_mask: 10
    pretrained: true
  aspp:
    in_channels: 512
    out_channels: 512
  decoder: res_shortcut_inst_matt_spconv_22
  decoder_args:
    atten_block: 2
    atten_dim: 128
    atten_head: 1
    atten_stride: 1
    detail_mask_dropout: 0.1
    final_channel: 64
    freeze_detail_branch: false
    head_channel: 120
    max_inst: 10
    use_id_pe: true
    warmup_detail_iter: 3000
    warmup_mask_atten_iter: 0
  
  loss_alpha_w: 1.0
  loss_alpha_type: l1
  loss_alpha_grad_w: 0.05
  loss_alpha_lap_w: 0.05
  loss_atten_w: 5.0
  loss_reweight_os8: true
  loss_dtSSD_w: 0.0
  
name: maggie_image_cvpr24
output_dir: output/image
test:
  batch_size: 1
  log_iter: 100
  metrics:
  - MAD
  - MSE
  - SAD
  - Grad
  - Conn
  num_workers: 4
  postprocessing: false
  save_dir: output/image/maggie_image_cvpr24/vis
  save_results: false
train:
  batch_size: 12
  log_iter: 10
  max_iter: 52000
  num_workers: 8
  optimizer:
    betas:
    - 0.9
    - 0.999
    lr: 0.00015
    momentum: 0.9
    name: adamw
    weight_decay: 0.01
  resume: ''
  resume_last: false
  scheduler:
    gamma: 0.1
    name: cosine
    power: 0.9
    step_size: 10000
    warmup_iters: 1000
  seed: 1234
  val_best_metric: MAD
  val_dist: true
  val_iter: 500
  val_metrics:
  - MAD
  - MSE
  - SAD
  vis_iter: 50
wandb:
  entity: research
  id: ''
  project: maggie
  use: true
