dataset:
  test:
    name: HIM
    root_dir: data/HIM2K_M-HIM2K
    split: comp
    short_size: 576
    downscale_mask: false
    alpha_dir_name: alphas
    mask_dir_name: masks_matched_r50_fpn_3x
  train:
    name: HIM
    root_dir: data
    split: I-HIM50K
    short_size: 576
    random_state: 2023
    max_inst: 1
    crop:
    - 512
    - 512
    padding_crop_p: 0.1
    flip_p: 0.5
    gamma_p: 0.5
    add_noise_p: 0.3
    jpeg_p: 0.1
    affine_p: 0.1
    binarized_kernel: 30
    downscale_mask_p: 0.5
    mask_dir_name: ''
    alpha_dir_name: alphas
model:
  arch: MGM_SingInst
  weights: checkpoints/mgm.pth
  sync_bn: true
  having_unused_params: false
  warmup_iters: 1125
  encoder: res_shortcut_29
  encoder_args:
    num_embed: 3
    num_mask: 1
    pretrained: true
  aspp:
    in_channels: 512
    out_channels: 512
  decoder: res_shortcut_22
  decoder_args:
    max_inst: 1
  
  loss_alpha_w: 1.0
  loss_alpha_type: l1
  loss_alpha_grad_w: 0.05
  loss_alpha_lap_w: 0.05
  loss_atten_w: 0.0
  loss_reweight_os8: false
  loss_dtSSD_w: 0.0
  
name: mgm_cvpr24
output_dir: output/image
test:
  batch_size: 1
  log_iter: 100
  metrics:
  - MAD
  - MSE
  - SAD
  - Grad
  - Conn
  num_workers: 4
  postprocessing: false
  save_dir: output/image/mgm_cvpr24/vis
  save_results: false
train:
  batch_size: 32
  log_iter: 10
  max_iter: 40000
  num_workers: 8
  optimizer:
    betas:
    - 0.9
    - 0.999
    lr: 0.00015
    momentum: 0.9
    name: adamw
    weight_decay: 0.01
  resume: ''
  resume_last: false
  scheduler:
    gamma: 0.1
    name: cosine
    power: 0.9
    step_size: 10000
    warmup_iters: 1000
  seed: 1234
  val_best_metric: MAD
  val_dist: true
  val_iter: 500
  val_metrics:
  - MAD
  - MSE
  - SAD
  vis_iter: 50
wandb:
  entity: research
  id: ''
  project: maggie
  use: true
