name: 'baseline_rn34'
model:
  dynamic_kernel:
    out_incoherence: 157
    out_pixeldecoder: 64
    in_features:
      - os32
      - os16
      - os8
  breakdown:
    in_features:
      - os4
      - os1
train:
  optimizer:
    lr: 0.0002
    name: adamw
  val_iter: 100
  vis_iter: 50
  log_iter: 10
output_dir: 'output'
dataset:
  train:
    root_dir: '/mnt/localssd/VideoMatte240K'
    bg_dir: '/mnt/localssd/bg'
    short_size: 768
  test:
    root_dir: '/mnt/localssd/VideoMatte240K'
    short_size: 768