# Refer to utils/config.py for definition and options.

version = "InstMatt-stage1"
dist = true

[model]
trimap_channel = 1
mask_channel = 3
batch_size = 4
imagenet_pretrain = true
imagenet_pretrain_path = "/home/chuongh/vm2m/pretrain/model_best_resnet34_En_nomixup.pth"
self_refine_width1 = 30
self_refine_width2 = 15
    [model.arch]
    encoder = "res_shortcut_encoder_29"
    decoder = "res_shortcut_decoder_22_3ch"

[train]
total_step = 200000
warmup_step = 2000
val_step = 1000
clip_grad = true
G_lr = 1e-4
min_lr = 1e-5
rec_weight = 1.0
lap_weight = 1.0
comp_weight = 1.0
alpha_weight = 1.0
# Uncomment to resume training
# resume_checkpoint = "latest_model"
# reset_lr = false

[data]
train_alpha = "datasets/HIM50K_alpha.txt"
train_merged = "datasets/HIM50K_image.txt"
train_mask = "datasets/HIM50K_mask.txt"
train_fg = "datasets/HIM50K_fg.txt"
train_bg = "datasets/HIM50K_bg.txt"
test_alpha = "datasets/HIM2K_comp_alphas.txt"
test_merged = "datasets/HIM2K_comp_image.txt"
test_mask = "datasets/HIM2K_comp_mask.txt"
workers = 6
crop_size = 640
cutmask_prob = 0.25
augmentation = true
random_interp = true
real_world_aug = false
vertical_flip = false
mask_random_sampling = 0.2

[log]
tensorboard_path = "./logs/tensorboard"
tensorboard_step = 100
tensorboard_image_step = 100
logging_path = "./logs/stdout"
logging_step =  10
logging_level = "INFO"
checkpoint_path = "./checkpoints"
checkpoint_step = 1000