name: 'mgm_enc-dec_spconv_temp'
train:
  batch_size: 6
  num_workers: 4
  max_iter: 100000
  optimizer:
    lr: 1.0e-4
    name: adamw
  scheduler:
    name: cosine
    warmup_iters: 1000
  val_metrics: ['MAD', 'MSE', 'dtSSD']
  val_best_metric: 'MAD'
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
model:
  arch: 'MGM'
  weights: output/HIM/mgm_enc-dec-spconv_him_syn_short-576-512x512_bs256_20k_adamw_5.0e-5/best_model.pth
  backbone: res_embed_shortcut_os8_encoder_29
  backbone_args:
    num_embed: 3
    num_mask: 10
    pretrained: true
  decoder: res_shortcut_attention_spconv_decoder_22
  decoder_args:
    atten_block: 2
    atten_dim: 128
    atten_head: 1
    atten_stride: 1
    final_channel: 64
    head_channel: 120
    max_inst: 10
    use_atten_mask: false
  mgm:
    warmup_iter: 10000
  loss_alpha_grad_w: 0.0
  loss_alpha_lap_w: 1.0
  loss_alpha_type: l1
  loss_alpha_w: 1.0
  loss_atten_w: 0.0
  loss_comp_w: 0.0
  loss_dtSSD_w: 1.0
  loss_multi_inst_w: 0.25
  loss_multi_inst_type: smooth_l1_0.5
  loss_multi_inst_warmup: 0
output_dir: 'output/polarized_matting'
test:
  num_workers: 4
  batch_size: 1
  metrics: ['MAD', 'MSE', 'SAD', 'dtSSD']
dataset:
  train:
    root_dir: '/mnt/localssd/polarized_matting'
    bg_dir: '/mnt/localssd/bg'
    short_size: 576
    clip_length: 1
  test:
    root_dir: '/mnt/localssd/polarized_matting'
    short_size: 576
    clip_length: 1
    clip_overlap: 0