name: 'vm2m0711'
model:
  arch: 'VM2M0711'
  weights: 'output/HHM/vm2m0711_hhm_short-768-512x512_bs32_50k_adamw_2e-4/best_model.pth'
  backbone: 'res_shortcut_encoder_29'
  backbone_args:
    num_mask: 0
  dynamic_kernel:
    out_incoherence: 137
    out_pixeldecoder: 864
  mgm:
    warmup_iter: 0
  loss_dtSSD_w: 1.0
  loss_comp_w: 1.0
train:
  optimizer:
    lr: 0.0001
    name: adamw
  val_metrics: ['MAD', 'MSE', 'dtSSD']
  val_best_metric: 'MAD'
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
  batch_size: 3
  num_workers: 10
  max_iter: 100000
output_dir: 'output/polarized_matting'
test:
  num_workers: 4
  batch_size: 1
dataset:
  train:
    root_dir: '/mnt/localssd/polarized_matting'
    bg_dir: '/mnt/localssd/bg'
    short_size: 768
    clip_length: 1
  test:
    root_dir: '/mnt/localssd/polarized_matting'
    short_size: 768
    clip_length: 8
    clip_overlap: 2