name: 'vm2m'
model:
  weights: 'output/HHM/vm2m_hmm_short-768-512x512_bs16_100k_adamw_2e-4/best_model.pth'
  dynamic_kernel:
    out_incoherence: 157
    out_pixeldecoder: 64
    in_features:
      - os32
      - os16
      - os8
  breakdown:
    in_features:
      - os4
      - os1
train:
  optimizer:
    lr: 0.0001
    name: adamw
  val_iter: 1000
  vis_iter: 200
  log_iter: 50
  batch_size: 4
  num_workers: 12
output_dir: 'output/polarized_matting'
test:
  num_workers: 4
  batch_size: 1
dataset:
  train:
    root_dir: '/mnt/localssd/polarized_matting'
    bg_dir: '/mnt/localssd/bg'
    short_size: 768
    clip_length: 1
  test:
    root_dir: '/mnt/localssd/polarized_matting'
    short_size: 768
    clip_length: 8
    clip_overlap: 2